apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.5.0
    chart: mongodb
    helm:
      values: |
        architecture: standalone
        auth:
          enabled: false # Disable authentication for testing (not recommended for production)
        persistence:
          enabled: true
          size: 10Gi
          storageClass: standard # Replace with your storage class
  destination:
    server: https://kubernetes.default.svc
    namespace: powersync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
