apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doppler-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DopplerHQ/kubernetes-operator.git'
    targetRevision: main
    path: config/default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: doppler-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true