# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: node-app          
#   namespace: argocd        
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/ydeyeq/k8s-tryouts-apps.git 
#     targetRevision: HEAD                                     
#     path: apps/Munch-dish-Saas
#   destination:
#     server: https://kubernetes.default.svc                  
#     namespace: default                                       
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
