apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  rules:
  - host: ydargocd.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80



# ---              


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: argocd-assets-ingress
#   namespace: argocd
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /assets/
#         pathType: Prefix
#         backend:
#           service:
#             name: argocd-server
#             port:
#               number: 80
#       - path: /api/
#         pathType: Prefix
#         backend:
#           service:
#             name: argocd-server
#             port:
#               number: 80
#       - path: /extensions.js/
#         pathType: Prefix
#         backend:
#           service:
#             name: argocd-server
#             port:
#               number: 80              