apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-http-docker
  namespace: default
  labels:
    app: node-app-http-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-http-docker
  template:
    metadata:
      labels:
        app: node-app-http-docker
    spec:
      containers:
      - name: node-app-http-docker
        image: ghcr.io/ydeyeq/node-app-http-docker:main 
        ports:
        - containerPort: 8080


---


apiVersion: v1
kind: Service
metadata:
  name: http-docker
spec:
  selector:
    app: node-app-http-docker
  ports:
    - port: 80
      targetPort: 8080


---


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: http-docker-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /httpdocker
#         pathType: Prefix
#         backend:
#           service:
#             name: http-docker
#             port:
#               number: 80
